language: python

sudo: false

env:
  global:
    - secure: "GwGXiVnRyn2i+dKe4BeAh7IwvNBQR5glpUO06/KAgqnVQf5k3m463ORJdPfhdnyPjogkC1Qxk30LaxyqKxa64RsmRQCqRxWU4PAI3BBbWczb+NnspO9Lk5Z7hsSFYJktdQWLGdP6LcxAfqsrWuej8ROXOoIVUP1L3waotcdSfYjOK09754rlPOQtUrG0lDdXEMktqI96rnW7puPLuFdqkv4FgZ/lq0dWXdkuKMOL6FcxVLl7oWzr6dypuIa+DkIg2nCN598PmnWKsTP4tRXwqoHoP9kBNICimQhs8U0vHRkgPVMnyvok1Xodrdl3Q5chYYlYzpN8STK+fibcNHfhoGexndAwQJlsJ60bcivKN0JWrqoP+L4E97zGpmBpZ1kz+Q+M3XxyRnwl28Dth3sf19ktnEScaA5aRTf3VmcWLV3RwYdDgL3ViMlJr3QIQNW0+Y2W45s37G7YjVmnhFJPyApCshw92vX6Su49/ButOdjlYge0SbgkxEs1/WgMVvGxqZ70CvoTyMNmOr+hjGSwQ/rHWCU3YikIb/wEkYRAsPlDJpfZM7rnGmTbOeDHLCfggE5r7qZEHmjGX6LwwP44bozI3u6k5azVFl2f8a39HlW+vZtFnyMYLDQgVx3One9Uc9UTfgiygxlw4aOCJwd2H1ISUR57VBQsReEipLRrcmw="

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TEST_TARGET=default
    - python: 3.5
      env: TEST_TARGET=default
    - python: 3.6
      env: TEST_TARGET=default
    - python: 3.6
      env: TEST_TARGET=coding_standards
    - python: 3.6
      env: TEST_TARGET=docs
  allow_failures:
    - python: 3.6
      env: TEST_TARGET=coding_standards
    - python: 3.6
      env: TEST_TARGET=docs

before_install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=https://repo.continuum.io/miniconda/Miniconda3
  - export MINICONDA_VERSION=latest
  - wget ${CONDA_BASE}-${MINICONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Setup conda
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda

  # Add 3rd party channels
  # ------------------------------------
  - conda config --add channels axiom-data-science
  - conda config --add channels conda-forge

  # Create our environment
  # ------------------------------------
  - ENV_NAME='test-environment'
  - conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION
  - source activate $ENV_NAME

  # Install testing requirements
  # ------------------------------------
  - conda install --file requirements.txt --file gutils/tests/requirements.txt
  - conda list --export

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install gutils-${version}.tar.gz && popd

script:
  - set -e

  - if [[ $TEST_TARGET == "default" ]]; then
      py.test --disable-warnings -m "not long" ;
    fi

  - if [[ $TEST_TARGET == "coding_standards" ]]; then
      py.test --disable-warnings --pep8 -m pep8 ;
      py.test --disable-warnings --flakes -m flakes ;
    fi

  - if [[ $TEST_TARGET == 'docs' ]]; then
      ./docs/deploy.sh ;
    fi

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ] && [ "$TEST_TARGET" == "default" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
      conda install -n root conda-build=3 conda=4.4 anaconda-client ;
      conda build conda-recipe;
      anaconda -t $ANACONDA_TOKEN upload --force -u axiom-data-science $HOME/miniconda/**/gutils-*.tar.bz2 ;
    fi

deploy:
  provider: releases
  api_key:
    secure: 76K3ayTtDeEyEhtOftO3EnAOpg0uQ3vM+0rS7lr9O7otAbP3Kb4U37fPezqVMfFsjgy+J3EXqtpkIMMBj++Y+wRJV9NH1KXuNaro9OWjzXomvP3+O24qhDTwO5IWrqrApvTMaDUEcjysZ72PbY8KUysOp5xtsDAeNidJg7C5XOEITVeT2yqHKVmaVK+ndDEGtM71hzHCP5swx44fiqQ9LwWM2OI+OuozJHiBBE6uMgp/4OLX5vv61K71eADfsm9RyQe2+PqrBFfXUCWVSwPyuKBWM6YkjuSl6UpMJH5y+Q9iPP6sFZi31RfDbMG3s5rr5Qbi1+lIiKsVDfFWcU+O/jJqtfbgeNu/QsGL70Xu9iJhnioKE6QEDWbfwgeIsXhpXcd8VvTiW7HAWn244naFMcDvWhbXc28kv/NRWgh8rYI+gXg4m9ugK6XgrVc6ywY4/zRvWNpaarFciDiaYH0/rW3bmmiIVdS84FGiwYl/rjlkQtorvbo5PMUTa5VQDmZGICYHbFV5FEf1fyIHJCi+6k4yobGCg8KxaVJW3g6hONqdKX8rGmWlxCYHE+3eShNxGb/QndqP2XeorTeg2BCWTpqrvPeYWfqqfu9CSTzlDdaPNjxPp2qDiZpQ5y2gcBiT3wRXdY1ju+E3EBOYk8lE/XgdG7fAtJ5Yfs8lgwa8nZA=
  on:
    tags: true
